management:
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: false
    db:
      enabled: true

server:
  port: ${PORT:8080}

spring:
  jpa:
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
